// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh41rfilWxrlBcXI4NFeyGbU8m5nMMy_0',
    appId: '1:762568181797:web:816f6f86a4b60ac71957cc',
    messagingSenderId: '762568181797',
    projectId: 'gymform2',
    authDomain: 'gymform2.firebaseapp.com',
    storageBucket: 'gymform2.firebasestorage.app',
    measurementId: 'G-NCD8EXM92N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD7Lq8DbD7H-LdpZw42rbuH_DUSOBFyKo',
    appId: '1:762568181797:android:4bbd393bf4dcab691957cc',
    messagingSenderId: '762568181797',
    projectId: 'gymform2',
    storageBucket: 'gymform2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCosAQm1WPmdcj0oDALANn10pRQv4OFke4',
    appId: '1:762568181797:ios:e33d17d515e4b37b1957cc',
    messagingSenderId: '762568181797',
    projectId: 'gymform2',
    storageBucket: 'gymform2.firebasestorage.app',
    iosBundleId: 'com.example.gymform3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCosAQm1WPmdcj0oDALANn10pRQv4OFke4',
    appId: '1:762568181797:ios:e33d17d515e4b37b1957cc',
    messagingSenderId: '762568181797',
    projectId: 'gymform2',
    storageBucket: 'gymform2.firebasestorage.app',
    iosBundleId: 'com.example.gymform3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh41rfilWxrlBcXI4NFeyGbU8m5nMMy_0',
    appId: '1:762568181797:web:8c2d589c55e406011957cc',
    messagingSenderId: '762568181797',
    projectId: 'gymform2',
    authDomain: 'gymform2.firebaseapp.com',
    storageBucket: 'gymform2.firebasestorage.app',
    measurementId: 'G-0SM76LXHKS',
  );
}
